export const LOGIN = 'LOGIN'
export const REGISTER = 'REGISTER'
export const LOGOUT = 'LOGOUT'
export const UPDATE_PROFILE = 'UPDATE_PROFILE'
export const LOGIN_ERROR = 'LOGIN_ERROR'
export const USER_LOADED = 'USER_LOADED'